platform :ios, '9.0'

target 'GKCycleScrollViewDemo' do
  use_frameworks!

  pod 'GKNavigationBarViewController'
  pod 'JXCategoryViewExt', :subspecs => ['Title', 'Indicator/Line']
  pod 'Masonry'
  pod 'SDAutoLayout'
  pod 'SDWebImage'

end
